# Preparación de Datos - Ejercicio - Publicidad y Ventas

**Contexto**  
Este conjunto de datos contiene las ventas obtenidas, de acuerdo al monto invertido en publicidad en diferentes canales.

**Contenido**  
El conjunto de datos proviene de kaggle: [Advertising dataset](https://www.kaggle.com/datasets/tawfikelmetwally/advertising-dataset).  
Contiene 200 renglones, con las siguientes columnas:
* TV: inversión de anuncios por TV, en miles de USD
* Radio: inversión de anuncios en radio, en miles de USD
* Newspaper: inversión de anuncios en periódicos, en miles de USD
* **Sales**: ventas obtenidas en millones de USD **->(variable objetivo)**

**Planteamiento del problema**  
Se busca predecir que canales tienen mayor impacto en las ventas obtenidas.

In [1]:
# Importar librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Cargar Datos

In [2]:
# Importar los datos
df = pd.read_csv('Advertising.csv')
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
# Renombrar columnas
df.columns = ['renglón', 'tv', 'radio', 'periodico', 'ventas']
df.head()

renglón     tv  radio  periodico  ventas
0        1  230.1   37.8       69.2    22.1
1        2   44.5   39.3       45.1    10.4
2        3   17.2   45.9       69.3     9.3
3        4  151.5   41.3       58.5    18.5
4        5  180.8   10.8       58.4    12.9

## Normalización

In [ ]:
# Variables independientes
## Escribe tu código aqui

tv  radio  periodico
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [ ]:
# Normalizar
## Escribe tu código aqui

[[ 9.69852266e-01  9.81522472e-01  1.77894547e+00]
 [-1.19737623e+00  1.08280781e+00  6.69578760e-01]
 [-1.51615499e+00  1.52846331e+00  1.78354865e+00]
 [ 5.20496822e-02  1.21785493e+00  1.28640506e+00]
 [ 3.94182198e-01 -8.41613655e-01  1.28180188e+00]
 [-1.61540845e+00  1.73103399e+00  2.04592999e+00]
 [-1.04557682e+00  6.43904671e-01 -3.24708413e-01]
 [-3.13436589e-01 -2.47406325e-01 -8.72486994e-01]
 [-1.61657614e+00 -1.42906863e+00 -1.36042422e+00]
 [ 6.16042873e-01 -1.39530685e+00 -4.30581584e-01]
 [-9.45155670e-01 -1.17923146e+00 -2.92486143e-01]
 [ 7.90028350e-01  4.96973404e-02 -1.22232878e+00]
 [-1.43908760e+00  7.99208859e-01  1.62704048e+00]
 [-5.78501712e-01 -1.05768905e+00 -1.07502697e+00]
 [ 6.66253447e-01  6.50657027e-01  7.11007392e-01]
 [ 5.64664612e-01  1.65000572e+00  1.02862691e+00]
 [-9.25304978e-01  9.00494200e-01  3.84117072e+00]
 [ 1.56887609e+00  1.10306488e+00  1.16211917e+00]
 [-9.08957349e-01 -1.86635121e-01 -5.64073843e-01]
 [ 3.00679600e-03  4.29449843e-

In [ ]:
# Variable dependiente
## Escribe tu código aqui

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: ventas, dtype: float64

In [7]:
print('X:', len(X_adj), 'y:', len(y))

X: 200 y: 200
