# Preparación de Datos - Ejemplo - Desempeño de Estudiantes

**Contexto**  
Este conjunto de datos contiene el desempeño de estudiantes, de acuerdo diversos factores.

**Contenido**  
El conjunto de datos proviene de kaggle: [Student Performance](https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression).  
Contiene 10,000 renglones, con las siguientes columnas:

| Variable                         | Definición                                       | Valor           |
| -------------------------------- | ------------------------------------------------ | --------------- |
| Hours Studied                    | Número total de horas dedicadas al estudio       | Numérico entero |
| Previous Scores                  | Calificaciones obtenidas en pruebas anteriores   | Numérico entero |
| Extracurricular Activities       | Participación en actividades extracurriculares   | Yes / No        |
| Sleep Hours                      | Horas de sueño por día                           | Numérico entero |
| Sample Question Papers Practiced | Exámenes muestra de práctica                     | Numérico entero |
| Performance Index                | Desempeño del estudiante **(variable objetivo)** | Entre 10 y 100  |

**Planteamiento del problema**  
Se busca encontrar que factores tienen mayor influencia en el desempeño de los estudiantes.

In [1]:
# Importar librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.preprocessing import StandardScaler

## Cargar Datos

In [2]:
# Importar los datos
df = pd.read_csv('Student_Performance.csv')
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [3]:
# Renombrar columnas
df.columns = ['horas_estudio', 'calificacion_anterior', 'actividades_extra', 'horas_sueño', 'preguntas_practica', 'desempeño']
df.head()

horas_estudio  calificacion_anterior actividades_extra  horas_sueño  \
0              7                     99               Yes            9   
1              4                     82                No            4   
2              8                     51               Yes            7   
3              5                     52               Yes            5   
4              7                     75                No            8   

   preguntas_practica  desempeño  
0                   1       91.0  
1                   2       65.0  
2                   2       45.0  
3                   2       36.0  
4                   5       66.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   horas_estudio          10000 non-null  int64  
 1   calificacion_anterior  10000 non-null  int64  
 2   actividades_extra      10000 non-null  object 
 3   horas_sueño            10000 non-null  int64  
 4   preguntas_practica     10000 non-null  int64  
 5   desempeño              10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


## One-hot encoding

In [5]:
print(df['actividades_extra'].unique())

['Yes' 'No']


In [6]:
df['actividades_extra'].value_counts()

No     5052
Yes    4948
Name: actividades_extra, dtype: int64

In [7]:
# One-hot encoding
df_adj = pd.get_dummies(df, columns=['actividades_extra'])
df_adj.head()

horas_estudio  calificacion_anterior  horas_sueño  preguntas_practica  \
0              7                     99            9                   1   
1              4                     82            4                   2   
2              8                     51            7                   2   
3              5                     52            5                   2   
4              7                     75            8                   5   

   desempeño  actividades_extra_No  actividades_extra_Yes  
0       91.0                     0                      1  
1       65.0                     1                      0  
2       45.0                     0                      1  
3       36.0                     0                      1  
4       66.0                     1                      0

In [8]:
# Eliminar columna extra
df_adj = df_adj[['horas_estudio', 'calificacion_anterior', 'actividades_extra_Yes', 'horas_sueño', 'preguntas_practica', 'desempeño']]
df_adj.columns = ['horas_estudio', 'calificacion_anterior', 'actividades_extra', 'horas_sueño', 'preguntas_practica', 'desempeño']
df_adj.head()

horas_estudio  calificacion_anterior  actividades_extra  horas_sueño  \
0              7                     99                  1            9   
1              4                     82                  0            4   
2              8                     51                  1            7   
3              5                     52                  1            5   
4              7                     75                  0            8   

   preguntas_practica  desempeño  
0                   1       91.0  
1                   2       65.0  
2                   2       45.0  
3                   2       36.0  
4                   5       66.0

## Normalización

In [9]:
# Variables independientes
X = df_adj[['horas_estudio', 'calificacion_anterior', 'actividades_extra', 'horas_sueño', 'preguntas_practica']]
X.head()

horas_estudio  calificacion_anterior  actividades_extra  horas_sueño  \
0              7                     99                  1            9   
1              4                     82                  0            4   
2              8                     51                  1            7   
3              5                     52                  1            5   
4              7                     75                  0            8   

   preguntas_practica  
0                   1  
1                   2  
2                   2  
3                   2  
4                   5

In [10]:
# Normalizar
scaler = StandardScaler()
X_adj = scaler.fit_transform(X)
print(X_adj)

[[ 0.77518771  1.70417565  1.01045465  1.45620461 -1.24975394]
 [-0.38348058  0.72391268 -0.98965352 -1.49229423 -0.90098215]
 [ 1.16141048 -1.06362569  1.01045465  0.27680507 -0.90098215]
 ...
 [ 0.38896495  0.7815752   1.01045465  0.86650484  0.1453332 ]
 [ 1.54763324  1.5888506   1.01045465  0.27680507 -1.59852572]
 [ 0.77518771  0.26261245 -0.98965352  0.86650484 -1.24975394]]


In [11]:
# Variable dependiente
y = df_adj['desempeño']
y.head()

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: desempeño, dtype: float64

In [12]:
print('X:', len(X_adj), 'y:', len(y))

X: 10000 y: 10000
